export const Colors = {
  blue: 'blue',
  white: 'white',
  lightblue: 'lightblue',
  orange: 'orange',
  red: 'red',
  lightgreen: 'lightgreen',
  purple: 'purple',
  gray: 'gray',
  brown: 'brown',
  green: 'green',
  lightpink: 'lightpink',
  palette: '#6096B4',
  palette1: '#93BFCF',
  palette2: '#BDCDD6',
  palette3: '#EEE9DA',
};
